import React from "react"
import type {Metadata} from "next";
import "./globals.css";
import {DarkModeProvider} from "@/context/DarkModeContext";
import {UserProvider} from "@/context/UserContext";
import {Toaster} from "sonner";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`bg-white dark:bg-gray-900 text-black dark:text-white transition-colors antialiased`}>
        <DarkModeProvider>
            <UserProvider>
                {children}
            </UserProvider>
        </DarkModeProvider>
        <Toaster
            richColors
            position={'bottom-left'}
            style={{fontFamily: 'IRANYekanX'}}
        />
        </body>
        </html>
    );
}
